# Generated by Django 5.2.4 on 2026-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=10, null=True),
        ),
    ]
