# Generated by Django 5.2.4 on 2026-03-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_employee_work_status_employee_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
