# Generated by Django 5.2.5 on 2026-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0009_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='employee/'),
        ),
    ]
